In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("D:/Airlines_Data_Analytics_Uncleaned.csv")

In [4]:
df.head()

,Flight_ID,Flight_Date,Airline,Origin,Destination,Flight_Status,Passenger_Count,Ticket_Price_INR,Flight_Duration_Min,Distance_KM,Booking_Channel,Cabin_Class,Aircraft_Type,Baggage_Allowance_KG,Internal_Note
0,FL0001,24-11-2025,Air India,Chennai,Hyderabad,Delayed,102,11644,427,569,MOBILE APP,BUSINESS,A320,35,Internal test
1,FL0002,17-01-2025,IndiGo,Delhi,Bengaluru,Delayed,174,41953,63,2448,Mobile App,BUSINESS,B787,20,Internal test
2,FL0003,29-10-2025,Akasa Air,Chennai,Goa,Cancelled,116,12689,160,4070,Travel Agent,Economy,A320,30,Routine flight
3,FL0004,03-07-2025,IndiGo,Hyderabad,Delhi,cancelled,162,37642,113,4135,Airport Counter,Economy,A350,25,NaN
4,FL0005,13-11-2025,IndiGo,Bengaluru,Mumbai,On Time,214,17435,445,1335,Website,Business,A320,30,Weather note

In [6]:
df.shape

(1000, 15)

In [7]:
df.isnull().sum()

Flight_ID                 0
Flight_Date               0
Airline                   0
Origin                    0
Destination               0
Flight_Status             0
Passenger_Count           3
Ticket_Price_INR          7
Flight_Duration_Min       0
Distance_KM               0
Booking_Channel           0
Cabin_Class               0
Aircraft_Type            25
Baggage_Allowance_KG      0
Internal_Note           183
dtype: int64

In [8]:
df.replace(["NULL", "N/A", "null", "n/a"], pd.NA, inplace=True)

,Flight_ID,Flight_Date,Airline,Origin,Destination,Flight_Status,Passenger_Count,Ticket_Price_INR,Flight_Duration_Min,Distance_KM,Booking_Channel,Cabin_Class,Aircraft_Type,Baggage_Allowance_KG,Internal_Note
0,FL0001,24-11-2025,Air India,Chennai,Hyderabad,Delayed,102,11644,427,569,MOBILE APP,BUSINESS,A320,35,Internal test
1,FL0002,17-01-2025,IndiGo,Delhi,Bengaluru,Delayed,174,41953,63,2448,Mobile App,BUSINESS,B787,20,Internal test
2,FL0003,29-10-2025,Akasa Air,Chennai,Goa,Cancelled,116,12689,160,4070,Travel Agent,Economy,A320,30,Routine flight
3,FL0004,03-07-2025,IndiGo,Hyderabad,Delhi,cancelled,162,37642,113,4135,Airport Counter,Economy,A350,25,NaN
4,FL0005,13-11-2025,IndiGo,Bengaluru,Mumbai,On Time,214,17435,445,1335,Website,Business,A320,30,Weather note
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,FL0589,22-10-2025,IndiGo,Hyderabad,Chennai,DELAYED,59,12077,213,2038,MOBILE APP,Business,B737,20,Routine flight
996,FL0646,10-08-2025,SpiceJet,Hyderabad,Mumbai,Cancelled,56,10880,305,3720,Travel Agent,Premium Economy,B787,25,NaN
997,FL0562,07-05-2025,Vistara,Kolkata,Goa,DELAYED,101,41282,126,3892,website,Economy,B787,15,Routine flight
998,FL0752,02-10-2025,AIR INDIA,Chennai,Mumbai,on-time,276,16031,116,3715,Mobile App,Premium Economy,B787,40,NaN
999,FL0429,03-05-2025,Akasa Air,Hyderabad,Mumbai,ON TIME,113,29560,146,3645,Website,Business,A321,25,Routine flight

In [9]:
df["Aircraft_Type"] = df["Aircraft_Type"].fillna("Unknown")

df["Internal_Note"] = df["Internal_Note"].fillna("Not Available")

In [10]:
df["Passenger_Count"] = pd.to_numeric(
    df["Passenger_Count"], errors="coerce")

df["Passenger_Count"] = df["Passenger_Count"].fillna(
    df["Passenger_Count"].median()).astype(int)

In [11]:
df["Ticket_Price_INR"] = (
    df["Ticket_Price_INR"]
    .astype(str)
    .str.replace("₹", "", regex=False)
    .str.replace("INR", "", regex=False)
    .str.strip())

df["Ticket_Price_INR"] = pd.to_numeric(
    df["Ticket_Price_INR"], errors="coerce")

df["Ticket_Price_INR"] = df["Ticket_Price_INR"].fillna(
    df["Ticket_Price_INR"].median())

In [12]:
df.drop_duplicates(inplace=True)

In [14]:
df["Airline"] = df["Airline"].str.strip()

df["Origin"] = df["Origin"].str.strip()

df["Destination"] = df["Destination"].str.strip()

In [15]:
# Airline
df["Airline"] = df["Airline"].replace({
    "INDIGO": "IndiGo",
    "AIR INDIA": "Air India",
    "spicejet": "SpiceJet"})

#Flight Status
df["Flight_Status"] = df["Flight_Status"].replace({
    "on-time": "On Time",
    "ON TIME": "On Time",
    "DELAYED": "Delayed",
    "cancelled": "Cancelled"})

#Booking Channel
df["Booking_Channel"] = df["Booking_Channel"].replace({
    "website": "Website",
    "MOBILE APP": "Mobile App"})

#Cabin Class
df["Cabin_Class"] = df["Cabin_Class"].replace({
    "economy": "Economy",
    "BUSINESS": "Business"})

In [16]:
df["Flight_Date"] = pd.to_datetime(
    df["Flight_Date"],
    format="mixed",
    dayfirst=True,
    errors="coerce")

In [17]:
df["Flight_Date"] = df["Flight_Date"].fillna(
    df["Flight_Date"].median())

In [18]:
df.drop(columns=["Internal_Note"], inplace=True)

In [19]:
df.head()
df.shape
df.dtypes
df.isnull().sum()
df.duplicated().sum()

np.int64(0)

In [20]:
df.to_csv(
    "D:/Airlines_Data_Analytics_Cleaned.csv",
    index=False)